---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress-cip
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ingress-nginx.cloud.holisticsecurity.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-svc-cip
          servicePort: 5080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress-np
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hello-svc-np.cloud.holisticsecurity.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-svc-np
          servicePort: 5080
---