---
### Create a secret for HTTP Basic Auth
### htpasswd -bc auth your-usr your-pwd
### kubectl create secret generic http-basic-auth --from-file=auth -n kuard
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer-test"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: kuard-http-basic-auth
  namespace: kuard
spec:
  rules:
  - host: ingress-nginx.cloud.holisticsecurity.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kuard
          servicePort: 80
  tls:
  - hosts:
    - ingress-nginx.cloud.holisticsecurity.io
    secretName: kuard-secret-tls 
---