---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: letsencrypt-issuer-staging@intix.info
    privateKeySecretRef:  
      name: letsencrypt-issuer-privkey-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
