---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-issuer-test"
    #cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer-test"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: weave-scope-app-http-basic-auth
  namespace: weave
spec:
  rules:
  - host: weave-scope.cloud.holisticsecurity.io
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app-svc-np
          servicePort: 80
  tls:
  - hosts:
    - weave-scope.cloud.holisticsecurity.io
    secretName: weave-scope-app-secret-tls
---